### ISSUE TITLE
Play, pause and sync not working anymore

### ISSUE THREAD

**Issue by Ansem93** [videoparty/prime-chrome#40]
Hi,
I'm using this plugin on MS Edge (since it's the only browser supporting full hd on prime).
Since a week or two it doesn't work anymore. 
If I play or pause the video it won't do that on the other PC. Also if I use "back 10 seconds" or something like that it won't sync the time on the player.

EDIT: I saw now that there is a new release, probably I was on the old one yesterday. I'll check tomorrow and give a feedback!

**Comment by rabomarnix** [comment]
Hi Ansem,

Thank you for your tip on full HD, didn't know that! Version 0.8.4 has been released to the Chrome store. I've submitted the new version for Edge as well, but MS takes more time to review. I'll keep this issue open until the Edge plugin has been published too!

**Comment by marnixbent** [comment]
Hi Ansem,

Thank you for your tip on full HD, didn't know that! Version 0.8.4 has been released to the Chrome store, so that's fixed. I've just submitted the new version for Edge as well, but MS takes more time to review. I'll keep this issue open until the Edge plugin has been published too!

UPDATE: Microsoft's partner center is giving me errors so it might take more time. Please use a Chrome-based browser in the mean time.

**Comment by marnixbent** [comment]
0.8.4 was pushed successfully in the Edge addon store. Please feel free to provide any feedback. A review in the store is encouraged, thank you!
